language: php
php:
  - '7.4'

script:
  - php composer.phar create-project nfouka/lightframework && rm -rf lightframework
  - php composer.phar create-project nfouka/lightframework && rm -rf lightframework
  - php composer.phar create-project nfouka/lightframework && rm -rf lightframework
  - php composer.phar create-project nfouka/lightframework && rm -rf lightframework
  - php composer.phar create-project nfouka/lightframework && rm -rf lightframework
  - php composer.phar create-project nfouka/lightframework && rm -rf lightframework
  - php composer.phar create-project nfouka/lightframework && rm -rf lightframework
  - php composer.phar create-project nfouka/lightframework && rm -rf lightframework
  - php composer.phar create-project nfouka/lightframework && rm -rf lightframework
  - php composer.phar create-project nfouka/lightframework && rm -rf lightframework
  - php composer.phar create-project nfouka/lightframework && rm -rf lightframework
  - php composer.phar create-project nfouka/lightframework && rm -rf lightframework
