language: php
php:
  - '7.3'

script:
   - composer install
   - php composer.phar create-project nfouka/lightframework && rm -rf lightframework
   - php composer.phar create-project nfouka/lightframework && rm -rf lightframework
   - php composer.phar create-project nfouka/lightframework && rm -rf lightframework
   - php composer.phar create-project nfouka/lightframework && rm -rf lightframework
   - php composer.phar create-project nfouka/lightframework && rm -rf lightframework
   - php composer.phar create-project nfouka/lightframework && rm -rf lightframework
   - php composer.phar create-project nfouka/lightframework && rm -rf lightframework
   - php composer.phar create-project nfouka/lightframework && rm -rf lightframework
   - php composer.phar create-project nfouka/lightframework && rm -rf lightframework
   - php composer.phar create-project nfouka/lightframework && rm -rf lightframework
   - php composer.phar create-project nfouka/lightframework && rm -rf lightframework
   - php composer.phar create-project nfouka/lightframework && rm -rf lightframework
   - php composer.phar create-project nfouka/lightframework && rm -rf lightframework
   - php composer.phar create-project nfouka/lightframework && rm -rf lightframework
   - php composer.phar create-project nfouka/lightframework && rm -rf lightframework
